# Generated by Django 5.0.3 on 2024-03-14 20:08

import auctions.models
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Auction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('starting_price', models.DecimalField(decimal_places=2, max_digits=5)),
                ('auction_duration', models.PositiveIntegerField(default=0, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(20)])),
                ('image_url', models.ImageField(blank=True, null=True, upload_to=auctions.models.upload_to)),
            ],
        ),
    ]
