# Generated by Django 5.0.3 on 2024-03-16 10:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0004_alter_auction_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='auction',
            old_name='auto_now_add',
            new_name='updated_at',
        ),
    ]
