# Generated by Django 5.0.3 on 2024-04-08 10:28

import auctions.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_rename_auto_now_add_auction_updated_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='auction',
            name='image_url',
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to=auctions.models.upload_to),
        ),
    ]
