# Generated by Django 5.0.3 on 2024-04-24 17:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0006_alter_auction_image_url'),
        ('bid', '0002_alter_bid_bid_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='bids',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='auction', to='bid.bid'),
        ),
    ]
