# Generated by Django 5.0.3 on 2024-04-25 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auction_bids'),
    ]

    operations = [
        migrations.AddField(
            model_name='auction',
            name='is_finished',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
