# Generated by Django 5.0.4 on 2024-05-24 19:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_remove_auction_bids_auction_current_bid'),
        ('bid', '0006_alter_bid_bid_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bid',
            name='auction',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bids_auction', to='auctions.auction'),
        ),
    ]
